FROM fedora

RUN dnf -y install git meson gcc glib2-devel openssl-devel ncurses-devel perl-ExtUtils-Embed
RUN git clone http://github.com/irssi/irssi.git
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build