name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test tags'
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y meson ninja-build

    - name: Configure with Meson
      run: meson Build

    - name: Build and Install
      run: |
        ninja -C Build
        sudo ninja -C Build install
